version: "3.9"
services:
  bot-flask:
    build: .
    container_name: bot-flask
#    environment:
#      - BROKER_API_KEY=${BROKER_API_KEY}
#      - BROKER_SECRET_KEY=${BROKER_SECRET_KEY}
#      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
#      - CRYPTOBOT_API_TOKEN=${CRYPTOBOT_API_TOKEN}
    ports:
      - "8000:80"

